### ISSUE TITLE
View-change for PBFT

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#342]
- [x] Write view-change logic (#177, #178, #341)
- [x] ID support (#266)
- [x] Add timers to ensure liveness (#332)
- [x] Run unit tests, do protocol fuzzing (#331)

**Comment by kchristidis** [comment]
Taken care of and merged in the master branch.
